apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener-service
spec:
  replica: 1
  selector:
    matchLabel:
      app: listener-service
  template:
    metadata:
      labels:
        app: listener-service
    spec: 
      containers:
      - name: listener-service
        image: "gio/listener-service:1.0.0"
        env:
          - name: rabbitMQDial
            value: "amqp://guest:guest@rabbitmq"
        resources:
          requests:
            memory: "64Mi"
            cpu: "2500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata: 
  name: listener-service
spec:
  selector:
    app: listener-service
  ports:
    - protocol: TCP
      name: main-port
      port: 80
      targetPort: 80