apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-service
spec:
  replica: 1
  selector:
    matchLabel:
      app: mailer-service
  template:
    metadata:
      labels:
        app: mailer-service
    spec: 
      containers:
      - name: mailer-service
        image: "mail-service:1.0.0"
        resources:
          requests:
            memory: "128Mi"
            cpu: "2500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: MAIL_DOMAIN
            value: "localhost"
          - name: MAIL_HOST
            value: "localhost"
          - name: MAIL_PORT
            value: "1025"
          - name: MAIL_USERNAME
            value: ""
          - name: EMAIL_PASSWORD
            value: ""
          - name: MAIL_ENCRYPTION
            value: "none"
          - name: FROM_NAME
            value: "john Doe"
          - name: FROM_ADDRESS
            value: "jhon.Doe@email.com"
        ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata: 
  name: mailer-service
spec:
  selector:
    app: mailer-service
  ports:
    - protocol: TCP
      name: main-port
      port: 80
      targetPort: 80